# Generated by Django 5.1.2 on 2024-10-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
