# Generated by Django 5.1.2 on 2024-10-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='upvotes',
        ),
    ]
